---
- name: create ec2 launch config
  hosts: localhost
  connection: local
  tasks:
  - name: creating EC2 Launch Configuration for schedule service.
    ec2_lc:
      name: "{{ launch_config }}"
      image_id: ami-0d56878464c8947c3
      instance_type: t3.small
      vpc_id: vpc-035fdbc6b57c6319c
      assign_public_ip: yes
      volumes: 
      - device_name: /dev/xvda
        snapshot_id: snap-00e09bc5e904cba9f
        volume_size: 16
        volume_type: standard
        delete_on_termination: true
      - device_name: /dev/sdb
        snapshot: snap-07683f64befbd850e
        volume_size: 30
        volume_type: standard
        delete_on_termination: true
      security_groups: ['Service_WEB_SG']
      region: ap-south-1
      instance_profile_name: uat_service_role
      user_data_path: /home/ansible/scripts/user_data
    register: lc_info
  - debug: var=lc_info
...