---
- hosts: localhost
  connection: local
  tasks:
  - name: Delete Application Load Balancer
    elb_application_lb:
      name: "{{ elb_name }}"
      region: "{{ aws_region }}"
      state: absent
    register: elb_delete_info
  - debug: var=elb_delete_info
...

