---

- name: This is for hardening
  hosts: test
  remote_user: ec2-user
  become: true
  vars_files: 
    - vars/basevars.yaml
  roles: 
     - fail2ban
   # - aide.done
   # - clamav
   # - disable-root-login2.done
   # - iptables3
   # - password-auth.done
   #  - service-status-check

